export const JOB_COLUMNS = [
  "id",
  "created_at",
  "updated_at",
  "title",
  "company",
  "location",
  "remote",
  "employment_type",
  "seniority",
  "years_min",
  "years_max",
  "salary_min",
  "salary_max",
  "salary_currency",
  "category",
  "required_skills",
  "preferred_skills",
  "technologies",
  "description",
  "apply_url",
  "status",
  "source",
] as const;
