/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as MigrateRouteImport } from './routes/migrate'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as AdminIdRouteImport } from './routes/admin_.$id'
import { Route as AdminAnalyticsRouteImport } from './routes/admin_.analytics'
import { Route as AdminJobsRouteImport } from './routes/admin_.jobs'
import { Route as AdminMatchingRouteImport } from './routes/admin_.matching'
import { Route as ApiApplicantsRouteImport } from './routes/api/applicants'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'
import { Route as JobsIdRouteImport } from './routes/jobs_.$id'
import { Route as ProfileIdRouteImport } from './routes/profile_.$id'
import { Route as ApiAdminAnalyticsRouteImport } from './routes/api/admin.analytics'
import { Route as ApiAdminApplicantsRouteImport } from './routes/api/admin.applicants'
import { Route as ApiAdminJobsRouteImport } from './routes/api/admin.jobs'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin.login'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin.logout'
import { Route as ApiAdminMatchingRouteImport } from './routes/api/admin.matching'
import { Route as ApiApplicantsIdRouteImport } from './routes/api/applicants.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiJobsIdRouteImport } from './routes/api/jobs.$id'
import { Route as ApiMatchesActionsRouteImport } from './routes/api/matches.actions'
import { Route as ApiMatchingRunRouteImport } from './routes/api/matching.run'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram.webhook'
import { Route as ApiAdminNotificationsRetryRouteImport } from './routes/api/admin.notifications.retry'
import { Route as ApiApplicantsIdCvRouteImport } from './routes/api/applicants.$id.cv'
import { Route as ApiMatchesApplicantApplicantIdRouteImport } from './routes/api/matches.applicant.$applicantId'
import { Route as ApiMatchesJobJobIdRouteImport } from './routes/api/matches.job.$jobId'
import { Route as ApiMatchingApplicantApplicantIdRouteImport } from './routes/api/matching.applicant.$applicantId'
import { Route as ApiMatchingJobJobIdRouteImport } from './routes/api/matching.job.$jobId'
import { Route as ApiAdminApplicantsIdCvRouteImport } from './routes/api/admin.applicants.$id.cv'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrateRoute = MigrateRouteImport.update({
  id: '/migrate',
  path: '/migrate',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdRoute = AdminIdRouteImport.update({
  id: '/admin_/$id',
  path: '/admin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin_/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin_/jobs',
  path: '/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMatchingRoute = AdminMatchingRouteImport.update({
  id: '/admin_/matching',
  path: '/admin/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplicantsRoute = ApiApplicantsRouteImport.update({
  id: '/api/applicants',
  path: '/api/applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs_/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile_/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAnalyticsRoute = ApiAdminAnalyticsRouteImport.update({
  id: '/api/admin/analytics',
  path: '/api/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminApplicantsRoute = ApiAdminApplicantsRouteImport.update({
  id: '/api/admin/applicants',
  path: '/api/admin/applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminJobsRoute = ApiAdminJobsRouteImport.update({
  id: '/api/admin/jobs',
  path: '/api/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMatchingRoute = ApiAdminMatchingRouteImport.update({
  id: '/api/admin/matching',
  path: '/api/admin/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplicantsIdRoute = ApiApplicantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiApplicantsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdRoute = ApiJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiJobsRoute,
} as any)
const ApiMatchesActionsRoute = ApiMatchesActionsRouteImport.update({
  id: '/api/matches/actions',
  path: '/api/matches/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchingRunRoute = ApiMatchingRunRouteImport.update({
  id: '/api/matching/run',
  path: '/api/matching/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminNotificationsRetryRoute =
  ApiAdminNotificationsRetryRouteImport.update({
    id: '/api/admin/notifications/retry',
    path: '/api/admin/notifications/retry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiApplicantsIdCvRoute = ApiApplicantsIdCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => ApiApplicantsIdRoute,
} as any)
const ApiMatchesApplicantApplicantIdRoute =
  ApiMatchesApplicantApplicantIdRouteImport.update({
    id: '/api/matches/applicant/$applicantId',
    path: '/api/matches/applicant/$applicantId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMatchesJobJobIdRoute = ApiMatchesJobJobIdRouteImport.update({
  id: '/api/matches/job/$jobId',
  path: '/api/matches/job/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchingApplicantApplicantIdRoute =
  ApiMatchingApplicantApplicantIdRouteImport.update({
    id: '/api/matching/applicant/$applicantId',
    path: '/api/matching/applicant/$applicantId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMatchingJobJobIdRoute = ApiMatchingJobJobIdRouteImport.update({
  id: '/api/matching/job/$jobId',
  path: '/api/matching/job/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminApplicantsIdCvRoute = ApiAdminApplicantsIdCvRouteImport.update({
  id: '/$id/cv',
  path: '/$id/cv',
  getParentRoute: () => ApiAdminApplicantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/jobs': typeof JobsRoute
  '/migrate': typeof MigrateRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/success': typeof SuccessRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/matching': typeof AdminMatchingRoute
  '/api/applicants': typeof ApiApplicantsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/jobs/$id': typeof JobsIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/api/admin/analytics': typeof ApiAdminAnalyticsRoute
  '/api/admin/applicants': typeof ApiAdminApplicantsRouteWithChildren
  '/api/admin/jobs': typeof ApiAdminJobsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/matching': typeof ApiAdminMatchingRoute
  '/api/applicants/$id': typeof ApiApplicantsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/matches/actions': typeof ApiMatchesActionsRoute
  '/api/matching/run': typeof ApiMatchingRunRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/admin/notifications/retry': typeof ApiAdminNotificationsRetryRoute
  '/api/applicants/$id/cv': typeof ApiApplicantsIdCvRoute
  '/api/matches/applicant/$applicantId': typeof ApiMatchesApplicantApplicantIdRoute
  '/api/matches/job/$jobId': typeof ApiMatchesJobJobIdRoute
  '/api/matching/applicant/$applicantId': typeof ApiMatchingApplicantApplicantIdRoute
  '/api/matching/job/$jobId': typeof ApiMatchingJobJobIdRoute
  '/api/admin/applicants/$id/cv': typeof ApiAdminApplicantsIdCvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/jobs': typeof JobsRoute
  '/migrate': typeof MigrateRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/success': typeof SuccessRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/matching': typeof AdminMatchingRoute
  '/api/applicants': typeof ApiApplicantsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/jobs/$id': typeof JobsIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/api/admin/analytics': typeof ApiAdminAnalyticsRoute
  '/api/admin/applicants': typeof ApiAdminApplicantsRouteWithChildren
  '/api/admin/jobs': typeof ApiAdminJobsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/matching': typeof ApiAdminMatchingRoute
  '/api/applicants/$id': typeof ApiApplicantsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/matches/actions': typeof ApiMatchesActionsRoute
  '/api/matching/run': typeof ApiMatchingRunRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/admin/notifications/retry': typeof ApiAdminNotificationsRetryRoute
  '/api/applicants/$id/cv': typeof ApiApplicantsIdCvRoute
  '/api/matches/applicant/$applicantId': typeof ApiMatchesApplicantApplicantIdRoute
  '/api/matches/job/$jobId': typeof ApiMatchesJobJobIdRoute
  '/api/matching/applicant/$applicantId': typeof ApiMatchingApplicantApplicantIdRoute
  '/api/matching/job/$jobId': typeof ApiMatchingJobJobIdRoute
  '/api/admin/applicants/$id/cv': typeof ApiAdminApplicantsIdCvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/jobs': typeof JobsRoute
  '/migrate': typeof MigrateRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/success': typeof SuccessRoute
  '/admin_/$id': typeof AdminIdRoute
  '/admin_/analytics': typeof AdminAnalyticsRoute
  '/admin_/jobs': typeof AdminJobsRoute
  '/admin_/matching': typeof AdminMatchingRoute
  '/api/applicants': typeof ApiApplicantsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/jobs_/$id': typeof JobsIdRoute
  '/profile_/$id': typeof ProfileIdRoute
  '/api/admin/analytics': typeof ApiAdminAnalyticsRoute
  '/api/admin/applicants': typeof ApiAdminApplicantsRouteWithChildren
  '/api/admin/jobs': typeof ApiAdminJobsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/matching': typeof ApiAdminMatchingRoute
  '/api/applicants/$id': typeof ApiApplicantsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/matches/actions': typeof ApiMatchesActionsRoute
  '/api/matching/run': typeof ApiMatchingRunRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/admin/notifications/retry': typeof ApiAdminNotificationsRetryRoute
  '/api/applicants/$id/cv': typeof ApiApplicantsIdCvRoute
  '/api/matches/applicant/$applicantId': typeof ApiMatchesApplicantApplicantIdRoute
  '/api/matches/job/$jobId': typeof ApiMatchesJobJobIdRoute
  '/api/matching/applicant/$applicantId': typeof ApiMatchingApplicantApplicantIdRoute
  '/api/matching/job/$jobId': typeof ApiMatchingJobJobIdRoute
  '/api/admin/applicants/$id/cv': typeof ApiAdminApplicantsIdCvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/jobs'
    | '/migrate'
    | '/privacy'
    | '/profile'
    | '/services'
    | '/sign-in'
    | '/sign-up'
    | '/success'
    | '/admin/$id'
    | '/admin/analytics'
    | '/admin/jobs'
    | '/admin/matching'
    | '/api/applicants'
    | '/api/health'
    | '/api/jobs'
    | '/jobs/$id'
    | '/profile/$id'
    | '/api/admin/analytics'
    | '/api/admin/applicants'
    | '/api/admin/jobs'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/matching'
    | '/api/applicants/$id'
    | '/api/auth/$'
    | '/api/jobs/$id'
    | '/api/matches/actions'
    | '/api/matching/run'
    | '/api/telegram/webhook'
    | '/api/admin/notifications/retry'
    | '/api/applicants/$id/cv'
    | '/api/matches/applicant/$applicantId'
    | '/api/matches/job/$jobId'
    | '/api/matching/applicant/$applicantId'
    | '/api/matching/job/$jobId'
    | '/api/admin/applicants/$id/cv'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/jobs'
    | '/migrate'
    | '/privacy'
    | '/profile'
    | '/services'
    | '/sign-in'
    | '/sign-up'
    | '/success'
    | '/admin/$id'
    | '/admin/analytics'
    | '/admin/jobs'
    | '/admin/matching'
    | '/api/applicants'
    | '/api/health'
    | '/api/jobs'
    | '/jobs/$id'
    | '/profile/$id'
    | '/api/admin/analytics'
    | '/api/admin/applicants'
    | '/api/admin/jobs'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/matching'
    | '/api/applicants/$id'
    | '/api/auth/$'
    | '/api/jobs/$id'
    | '/api/matches/actions'
    | '/api/matching/run'
    | '/api/telegram/webhook'
    | '/api/admin/notifications/retry'
    | '/api/applicants/$id/cv'
    | '/api/matches/applicant/$applicantId'
    | '/api/matches/job/$jobId'
    | '/api/matching/applicant/$applicantId'
    | '/api/matching/job/$jobId'
    | '/api/admin/applicants/$id/cv'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/jobs'
    | '/migrate'
    | '/privacy'
    | '/profile'
    | '/services'
    | '/sign-in'
    | '/sign-up'
    | '/success'
    | '/admin_/$id'
    | '/admin_/analytics'
    | '/admin_/jobs'
    | '/admin_/matching'
    | '/api/applicants'
    | '/api/health'
    | '/api/jobs'
    | '/jobs_/$id'
    | '/profile_/$id'
    | '/api/admin/analytics'
    | '/api/admin/applicants'
    | '/api/admin/jobs'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/matching'
    | '/api/applicants/$id'
    | '/api/auth/$'
    | '/api/jobs/$id'
    | '/api/matches/actions'
    | '/api/matching/run'
    | '/api/telegram/webhook'
    | '/api/admin/notifications/retry'
    | '/api/applicants/$id/cv'
    | '/api/matches/applicant/$applicantId'
    | '/api/matches/job/$jobId'
    | '/api/matching/applicant/$applicantId'
    | '/api/matching/job/$jobId'
    | '/api/admin/applicants/$id/cv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  JobsRoute: typeof JobsRoute
  MigrateRoute: typeof MigrateRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ServicesRoute: typeof ServicesRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SuccessRoute: typeof SuccessRoute
  AdminIdRoute: typeof AdminIdRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminMatchingRoute: typeof AdminMatchingRoute
  ApiApplicantsRoute: typeof ApiApplicantsRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiJobsRoute: typeof ApiJobsRouteWithChildren
  JobsIdRoute: typeof JobsIdRoute
  ProfileIdRoute: typeof ProfileIdRoute
  ApiAdminAnalyticsRoute: typeof ApiAdminAnalyticsRoute
  ApiAdminApplicantsRoute: typeof ApiAdminApplicantsRouteWithChildren
  ApiAdminJobsRoute: typeof ApiAdminJobsRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminMatchingRoute: typeof ApiAdminMatchingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMatchesActionsRoute: typeof ApiMatchesActionsRoute
  ApiMatchingRunRoute: typeof ApiMatchingRunRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
  ApiAdminNotificationsRetryRoute: typeof ApiAdminNotificationsRetryRoute
  ApiMatchesApplicantApplicantIdRoute: typeof ApiMatchesApplicantApplicantIdRoute
  ApiMatchesJobJobIdRoute: typeof ApiMatchesJobJobIdRoute
  ApiMatchingApplicantApplicantIdRoute: typeof ApiMatchingApplicantApplicantIdRoute
  ApiMatchingJobJobIdRoute: typeof ApiMatchingJobJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrate': {
      id: '/migrate'
      path: '/migrate'
      fullPath: '/migrate'
      preLoaderRoute: typeof MigrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/$id': {
      id: '/admin_/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AdminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/analytics': {
      id: '/admin_/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/jobs': {
      id: '/admin_/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/matching': {
      id: '/admin_/matching'
      path: '/admin/matching'
      fullPath: '/admin/matching'
      preLoaderRoute: typeof AdminMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/applicants': {
      id: '/api/applicants'
      path: '/api/applicants'
      fullPath: '/api/applicants'
      preLoaderRoute: typeof ApiApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs_/$id': {
      id: '/jobs_/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/$id': {
      id: '/profile_/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/analytics': {
      id: '/api/admin/analytics'
      path: '/api/admin/analytics'
      fullPath: '/api/admin/analytics'
      preLoaderRoute: typeof ApiAdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/applicants': {
      id: '/api/admin/applicants'
      path: '/api/admin/applicants'
      fullPath: '/api/admin/applicants'
      preLoaderRoute: typeof ApiAdminApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/jobs': {
      id: '/api/admin/jobs'
      path: '/api/admin/jobs'
      fullPath: '/api/admin/jobs'
      preLoaderRoute: typeof ApiAdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/matching': {
      id: '/api/admin/matching'
      path: '/api/admin/matching'
      fullPath: '/api/admin/matching'
      preLoaderRoute: typeof ApiAdminMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/applicants/$id': {
      id: '/api/applicants/$id'
      path: '/$id'
      fullPath: '/api/applicants/$id'
      preLoaderRoute: typeof ApiApplicantsIdRouteImport
      parentRoute: typeof ApiApplicantsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id': {
      id: '/api/jobs/$id'
      path: '/$id'
      fullPath: '/api/jobs/$id'
      preLoaderRoute: typeof ApiJobsIdRouteImport
      parentRoute: typeof ApiJobsRoute
    }
    '/api/matches/actions': {
      id: '/api/matches/actions'
      path: '/api/matches/actions'
      fullPath: '/api/matches/actions'
      preLoaderRoute: typeof ApiMatchesActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matching/run': {
      id: '/api/matching/run'
      path: '/api/matching/run'
      fullPath: '/api/matching/run'
      preLoaderRoute: typeof ApiMatchingRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/notifications/retry': {
      id: '/api/admin/notifications/retry'
      path: '/api/admin/notifications/retry'
      fullPath: '/api/admin/notifications/retry'
      preLoaderRoute: typeof ApiAdminNotificationsRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/applicants/$id/cv': {
      id: '/api/applicants/$id/cv'
      path: '/cv'
      fullPath: '/api/applicants/$id/cv'
      preLoaderRoute: typeof ApiApplicantsIdCvRouteImport
      parentRoute: typeof ApiApplicantsIdRoute
    }
    '/api/matches/applicant/$applicantId': {
      id: '/api/matches/applicant/$applicantId'
      path: '/api/matches/applicant/$applicantId'
      fullPath: '/api/matches/applicant/$applicantId'
      preLoaderRoute: typeof ApiMatchesApplicantApplicantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matches/job/$jobId': {
      id: '/api/matches/job/$jobId'
      path: '/api/matches/job/$jobId'
      fullPath: '/api/matches/job/$jobId'
      preLoaderRoute: typeof ApiMatchesJobJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matching/applicant/$applicantId': {
      id: '/api/matching/applicant/$applicantId'
      path: '/api/matching/applicant/$applicantId'
      fullPath: '/api/matching/applicant/$applicantId'
      preLoaderRoute: typeof ApiMatchingApplicantApplicantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matching/job/$jobId': {
      id: '/api/matching/job/$jobId'
      path: '/api/matching/job/$jobId'
      fullPath: '/api/matching/job/$jobId'
      preLoaderRoute: typeof ApiMatchingJobJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/applicants/$id/cv': {
      id: '/api/admin/applicants/$id/cv'
      path: '/$id/cv'
      fullPath: '/api/admin/applicants/$id/cv'
      preLoaderRoute: typeof ApiAdminApplicantsIdCvRouteImport
      parentRoute: typeof ApiAdminApplicantsRoute
    }
  }
}

interface ApiApplicantsIdRouteChildren {
  ApiApplicantsIdCvRoute: typeof ApiApplicantsIdCvRoute
}

const ApiApplicantsIdRouteChildren: ApiApplicantsIdRouteChildren = {
  ApiApplicantsIdCvRoute: ApiApplicantsIdCvRoute,
}

const ApiApplicantsIdRouteWithChildren = ApiApplicantsIdRoute._addFileChildren(
  ApiApplicantsIdRouteChildren,
)

interface ApiApplicantsRouteChildren {
  ApiApplicantsIdRoute: typeof ApiApplicantsIdRouteWithChildren
}

const ApiApplicantsRouteChildren: ApiApplicantsRouteChildren = {
  ApiApplicantsIdRoute: ApiApplicantsIdRouteWithChildren,
}

const ApiApplicantsRouteWithChildren = ApiApplicantsRoute._addFileChildren(
  ApiApplicantsRouteChildren,
)

interface ApiJobsRouteChildren {
  ApiJobsIdRoute: typeof ApiJobsIdRoute
}

const ApiJobsRouteChildren: ApiJobsRouteChildren = {
  ApiJobsIdRoute: ApiJobsIdRoute,
}

const ApiJobsRouteWithChildren =
  ApiJobsRoute._addFileChildren(ApiJobsRouteChildren)

interface ApiAdminApplicantsRouteChildren {
  ApiAdminApplicantsIdCvRoute: typeof ApiAdminApplicantsIdCvRoute
}

const ApiAdminApplicantsRouteChildren: ApiAdminApplicantsRouteChildren = {
  ApiAdminApplicantsIdCvRoute: ApiAdminApplicantsIdCvRoute,
}

const ApiAdminApplicantsRouteWithChildren =
  ApiAdminApplicantsRoute._addFileChildren(ApiAdminApplicantsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  JobsRoute: JobsRoute,
  MigrateRoute: MigrateRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ServicesRoute: ServicesRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SuccessRoute: SuccessRoute,
  AdminIdRoute: AdminIdRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminMatchingRoute: AdminMatchingRoute,
  ApiApplicantsRoute: ApiApplicantsRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiJobsRoute: ApiJobsRouteWithChildren,
  JobsIdRoute: JobsIdRoute,
  ProfileIdRoute: ProfileIdRoute,
  ApiAdminAnalyticsRoute: ApiAdminAnalyticsRoute,
  ApiAdminApplicantsRoute: ApiAdminApplicantsRouteWithChildren,
  ApiAdminJobsRoute: ApiAdminJobsRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminMatchingRoute: ApiAdminMatchingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMatchesActionsRoute: ApiMatchesActionsRoute,
  ApiMatchingRunRoute: ApiMatchingRunRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  ApiAdminNotificationsRetryRoute: ApiAdminNotificationsRetryRoute,
  ApiMatchesApplicantApplicantIdRoute: ApiMatchesApplicantApplicantIdRoute,
  ApiMatchesJobJobIdRoute: ApiMatchesJobJobIdRoute,
  ApiMatchingApplicantApplicantIdRoute: ApiMatchingApplicantApplicantIdRoute,
  ApiMatchingJobJobIdRoute: ApiMatchingJobJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
